# NumPy Tutorial

**Why is NumPy Faster in comparison to Lists?**

*   Faster to read less bytes of memory
*   No type checking during iteration through objects.
*   It uses contiguous memory in comparison to lists which uses scattered memory
*   Effective cache utilization

### Reference docs (https://docs.scipy.org/doc/numpy/reference/routines.linalg.html)








In [ ]:
pip install numpy

In [ ]:
import numpy as np

**Basics**

In [ ]:
a = np.array([1,2,3], dtype = "int16")
print(a)

[1 2 3]


In [ ]:
b = np.array([[1, 3, 5], [2, 4, 6]])
print(b)

[[1 3 5]
 [2 4 6]]


In [ ]:
#Get Dimension
b.ndim

2

In [ ]:
#Get Shape (Gives vector dimensions)
b.shape

(2, 3)

In [ ]:
#Get type (It can be set in the definition)
a.dtype

dtype('int16')

In [ ]:
#Number of elements
b.size

6

In [ ]:
c = np.array([[1,2,3,4,5,6,7,8],[9,10,11,12,13,14,15,16]])
print(c)

[[ 1  2  3  4  5  6  7  8]
 [ 9 10 11 12 13 14 15 16]]


In [ ]:
#Get a specific element
c[1,3]

12

In [ ]:
#Get a specific row
c[1,:]

array([ 9, 10, 11, 12, 13, 14, 15, 16])

In [ ]:
#Get a specific column
c[:, 5]

array([ 6, 14])

In [ ]:
## Getting a little more fancy [startindex:endindex:stepsize]
c[0, 1:-1:2]

array([2, 4, 6])

In [ ]:
c[1,5] = 20

c[:,2] = [1,2]
print(c)

[[ 1  2  1  4  5  6  7  8]
 [ 9 10  2 12 13 20 15 16]]


**Initializing Different Arrays**

In [ ]:
#All zeros
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [ ]:
np.zeros((4,5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [ ]:
np.zeros((2,3,3))

array([[[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]]])

In [ ]:
#All 1s
np.ones((3,2), dtype='int16')

array([[1, 1],
       [1, 1],
       [1, 1]], dtype=int16)

In [ ]:
#Any number all
np.full((3,3,3), 66)

array([[[66, 66, 66],
        [66, 66, 66],
        [66, 66, 66]],

       [[66, 66, 66],
        [66, 66, 66],
        [66, 66, 66]],

       [[66, 66, 66],
        [66, 66, 66],
        [66, 66, 66]]])

In [ ]:
# Random decimal numbers
np.random.rand(4,2)

array([[0.04445215, 0.50597906],
       [0.17220944, 0.15787003],
       [0.75577289, 0.23838274],
       [0.54505094, 0.03383333]])

In [ ]:
# Random Integer values
np.random.randint(-4,8, size=(3,3))

array([[-4,  6, -1],
       [ 5, -4,  4],
       [ 5,  5,  3]])

In [ ]:
# The identity matrix
np.identity(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [ ]:
# Repeat an array
arr = np.array([[1,2,3]])
r1 = np.repeat(arr,3, axis=0)
print(r1)

[[1 2 3]
 [1 2 3]
 [1 2 3]]


In [ ]:
output = np.ones((5,5))
print(output)

z = np.zeros((3,3))
z[1,1] = 9
print(z)

output[1:4,1:4] = z #Here 1:4 means rowns and columns to be included
print(output)

[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]
[[0. 0. 0.]
 [0. 9. 0.]
 [0. 0. 0.]]
[[1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 9. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1.]]




> `Careful with copying arrays`



In [ ]:
#Without copy() a will also change with b
a = np.array([1,2,3])
b = a.copy()
b[0] = 100

print(a)

[1 2 3]


**Maths and algebra**

In [ ]:
a = np.array([1,2,3,4])
print(a)

[1 2 3 4]


In [ ]:
a * 2

array([2, 4, 6, 8])

In [ ]:
# Take the sin
np.cos(a)

array([ 0.54030231, -0.41614684, -0.9899925 , -0.65364362])

In [ ]:
# Take the sin
np.sin(a)

array([ 0.84147098,  0.90929743,  0.14112001, -0.7568025 ])

In [ ]:
#Matrix multiplication
a = np.ones((2,3))
print(a)

b = np.full((3,2), 2)
print(b)

np.matmul(a,b)

[[1. 1. 1.]
 [1. 1. 1.]]
[[2 2]
 [2 2]
 [2 2]]


array([[6., 6.],
       [6., 6.]])

In [ ]:
# Find the determinant
c = np.identity(3)
np.linalg.det(c)

1.0